ci: Add script &CI to check dead links
eclipse-edc/eclipse-edc.github.io pull request #45
Opened 2024-12-19 02:43 UTC by liugddx

## What this PR changes/adds

## Why it does that

## Further notes

## Linked Issue(s)

Closes #39

2024-12-24 11:11 UTC, liugddx commented
PTAL @ndr-brt

2025-01-08 13:49 UTC, ndr-brt commented
added myself as a reviewer, could you put the PR in draft until it will be effectively ready for review? So I will be more proactive in reviewing it ;)

2025-02-10 11:24 UTC, liugddx commented
CI failure is caused by dead links

```
Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/
Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/dataFeed
Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedFrequency
Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedName
Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedType
Error: Dead link: http://w3id.org/starwars/context.jsonld
Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/
Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/faction
Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/name
Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/person
Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/webpage
Error: Dead link: https://app.swaggerhub.com/home?type=API
Error: Dead link: https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html
Error: Dead link: https://docs.sonarqube.org/latest/analysis/github-integration/
Error: Dead link: https://foo-industries.com/subcatalog
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/.github/PULL_REQUEST_TEMPLATE.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/.github/workflows/close-inactive-issues.yml
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/contribution_categories.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/docs/developer/data-plane-signaling/data-plane-signaling-token-handling.md#2-updates-to-thedataaddress-format
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/known_friends.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/styleguide.md
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/.github/ISSUE_TEMPLATE
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/docs/legal
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/docs/templates
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/extensions/common/api/management-api-json-ld-context
Error: Dead link: https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-04-open-telemetry/README.md
Error: Dead link: https://github.com/orgs/eclipse-edc/projects/3
Error: Dead link: https://identity.foundation/
Error: Dead link: https://identity.foundation/decentralized-web-node/spec/
Error: Dead link: https://identity.foundation/didcomm-messaging/spec/
Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/
Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition
Error: Dead link: https://identity.foundation/presentation-exchange/submission/v1
Error: Dead link: https://oss.sonatype.org/content/repositories/snapshots/
Error: Dead link: https://w3id.org/cx/v0.8/
Error: Dead link: https://w3id.org/idsa/v4.1/HTTP
Error: Dead link: https://w3id.org/starwars/v0.0.1/ns/faction
Error: Dead link: https://w3id.org/tractusx-trust/v0.8
```

2025-02-10 11:25 UTC, liugddx commented
![image](https://github.com/user-attachments/assets/9ef0795e-8f80-4c58-9501-efe5cff9bc3b)

2025-02-11 07:45 UTC, ndr-brt requested changes
> CI failure is caused by dead links
> 
> ```
> Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/
> Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/dataFeed
> Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedFrequency
> Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedName
> Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedType
> Error: Dead link: http://w3id.org/starwars/context.jsonld
> Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/
> Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/faction
> Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/name
> Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/person
> Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/webpage
> Error: Dead link: https://w3id.org/cx/v0.8/
> Error: Dead link: https://w3id.org/idsa/v4.1/HTTP
> Error: Dead link: https://w3id.org/starwars/v0.0.1/ns/faction
> Error: Dead link: https://w3id.org/tractusx-trust/v0.8
> ```

these are not proper links, these are jsonld namespaces and they don't need to be checked (as any url in a code block I'd say)

> ```
> Error: Dead link: https://identity.foundation/
> Error: Dead link: https://identity.foundation/decentralized-web-node/spec/
> Error: Dead link: https://identity.foundation/didcomm-messaging/spec/
> Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/
> Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition
> Error: Dead link: https://identity.foundation/presentation-exchange/submission/v1
> ```

these are proper links, why are they listed?

2025-02-11 11:15 UTC, liugddx commented
> > CI failure is caused by dead links
> > ```
> > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/
> > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/dataFeed
> > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedFrequency
> > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedName
> > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedType
> > Error: Dead link: http://w3id.org/starwars/context.jsonld
> > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/
> > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/faction
> > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/name
> > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/person
> > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/webpage
> > Error: Dead link: https://w3id.org/cx/v0.8/
> > Error: Dead link: https://w3id.org/idsa/v4.1/HTTP
> > Error: Dead link: https://w3id.org/starwars/v0.0.1/ns/faction
> > Error: Dead link: https://w3id.org/tractusx-trust/v0.8
> > ```
> 
> these are not proper links, these are jsonld namespaces and they don't need to be checked (as any url in a code block I'd say)
> 
> > ```
> > Error: Dead link: https://identity.foundation/
> > Error: Dead link: https://identity.foundation/decentralized-web-node/spec/
> > Error: Dead link: https://identity.foundation/didcomm-messaging/spec/
> > Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/
> > Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition
> > Error: Dead link: https://identity.foundation/presentation-exchange/submission/v1
> > ```
> 
> these are proper links, why are they listed?

![image](https://github.com/user-attachments/assets/2f9edee1-4eaf-4009-ba33-db0edb82fd32)

The result returned by testing identity.foundation is 403, I don't know what's causing this.

2025-02-11 11:19 UTC, liugddx commented
> > > CI failure is caused by dead links
> > > ```
> > > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/
> > > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/dataFeed
> > > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedFrequency
> > > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedName
> > > Error: Dead link: http://w3id.org/market-systems/v0.0.1/ns/feedType
> > > Error: Dead link: http://w3id.org/starwars/context.jsonld
> > > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/
> > > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/faction
> > > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/name
> > > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/person
> > > Error: Dead link: http://w3id.org/starwars/v0.0.1/ns/webpage
> > > Error: Dead link: https://w3id.org/cx/v0.8/
> > > Error: Dead link: https://w3id.org/idsa/v4.1/HTTP
> > > Error: Dead link: https://w3id.org/starwars/v0.0.1/ns/faction
> > > Error: Dead link: https://w3id.org/tractusx-trust/v0.8
> > > ```
> > 
> > 
> > these are not proper links, these are jsonld namespaces and they don't need to be checked (as any url in a code block I'd say)
> > > ```
> > > Error: Dead link: https://identity.foundation/
> > > Error: Dead link: https://identity.foundation/decentralized-web-node/spec/
> > > Error: Dead link: https://identity.foundation/didcomm-messaging/spec/
> > > Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/
> > > Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition
> > > Error: Dead link: https://identity.foundation/presentation-exchange/submission/v1
> > > ```
> > 
> > 
> > these are proper links, why are they listed?
> 
> ![image](https://private-user-images.githubusercontent.com/48236177/411942074-2f9edee1-4eaf-4009-ba33-db0edb82fd32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkyNzI4NTMsIm5iZiI6MTczOTI3MjU1MywicGF0aCI6Ii80ODIzNjE3Ny80MTE5NDIwNzQtMmY5ZWRlZTEtNGVhZi00MDA5LWJhMzMtZGIwZWRiODJmZDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjExVDExMTU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNzI3YWViNGRkM2YzNzhlZGM0YjUzZDRlZGEwMWQ3Mzg5NTZhM2QwNzFlNjRiMmRhNTcyNGQ4ZWIyZGIyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vpPElSfw9iwqmRjYLne3WH066ERoRzOG8ULD7t2CK_A)
> 
> The result returned by testing identity.foundation is 403, I don't know what's causing this.

This is the latest list.

```
Error: Dead link: https://docs.gradle.org/current/samples/sample_jvm_multi_project_with_code_coverage.html
Error: Dead link: https://docs.sonarqube.org/latest/analysis/github-integration/
Error: Dead link: https://foo-industries.com/subcatalog
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/.github/PULL_REQUEST_TEMPLATE.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/.github/workflows/close-inactive-issues.yml
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/contribution_categories.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/docs/developer/data-plane-signaling/data-plane-signaling-token-handling.md#2-updates-to-thedataaddress-format
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/known_friends.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md
Error: Dead link: https://github.com/eclipse-edc/Connector/blob/main/styleguide.md
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/.github/ISSUE_TEMPLATE
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/docs/legal
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/docs/templates
Error: Dead link: https://github.com/eclipse-edc/Connector/tree/main/extensions/common/api/management-api-json-ld-context
Error: Dead link: https://github.com/eclipse-edc/Samples/blob/main/transfer/transfer-04-open-telemetry/README.md
Error: Dead link: https://github.com/orgs/eclipse-edc/projects/3
Error: Dead link: https://identity.foundation/
Error: Dead link: https://identity.foundation/decentralized-web-node/spec/
Error: Dead link: https://identity.foundation/didcomm-messaging/spec/
Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/
Error: Dead link: https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition
Error: Dead link: https://identity.foundation/presentation-exchange/submission/v1
Error: Dead link: https://oss.sonatype.org/content/repositories/snapshots/
```

2025-02-11 12:48 UTC, ndr-brt requested changes
Deep diving into this, I'm usually in favor of home made solutions, but this looks fairly over-complicated. 
Why don't rely on already existing tools? With a brief search I found some of them, like [lychee](https://github.com/lycheeverse) (it also has a dedicated github action). I would consider those, because I don't know how much effort we want to put in the future in maintaining this script.

Plus, the `exclude_patterns.txt` it contains strings that are not "links", they are only url in the pages, and they shouldn't be taken into consideration at first

2025-04-25 15:05 UTC, mspiekermann commented
>I would consider those, because I don't know how much effort we want to put in the future in maintaining this script.

Agree. I had a look for an existing tool and found an [GitHub Action](https://github.com/UmbrellaDocs/action-linkspector) that uses _Linkspector_ and _Reviewdog_. I created an [example](https://github.com/mspiekermann/eclipse-edc.github.io ) on how this might be used. The action is triggered at PR creation and displays the errors in the workflow log and in the PR itself. There are further configuration options that might be useful (e.g. to limit to specific directories).

2025-05-10 18:08 UTC, mspiekermann reviewed
I checked the PR and  identified an issue we are jumping into, especially within this repo. As Hugo is doing some rendering work for us, this unfortunately causes many links to be identified as broken by the GitHub Actions, which actually are not. 

__This is not only an issue from this PR!__ It is also not lychee or linespector (same issue)!  Scripts are following their natural purpose and find a lot of links that are broken and they are from the plain source files. However, __they are not broken after rendering__ of the website's resources by Hugo.

For example, the Actions lists the logos in the root _index.md as `not found` with `src="/static/images/logos/huawei.logo.svg"`, which is correct because the logos are in `__/static/__images/logos/`. The rendered website displays the images without any issue. 

Another example is `content/en/documentation/for-contributors/control-plane/_index.md`, where links to `entity.md` are identified as `not found`. On the website entity.md is rendered by Hugo as there is the sub-directory `./entity`, which includes all linked files and resources. From the website, again links are working fine as `./entity/_index.md` is rendered into `entity.md`..  

I guess we need to find another approach of checking the links for this repository. Here such actions would just be usable for identifying links to other websites. With this approach, we are not really providing any support for contributors...

Any idea?

2025-05-11 04:09 UTC, liugddx commented
> I checked the PR and identified an issue we are jumping into, especially within this repo. As Hugo is doing some rendering work for us, this unfortunately causes many links to be identified as broken by the GitHub Actions, which actually are not.
> 
> **This is not only an issue from this PR!** It is also not lychee or linespector (same issue)! Scripts are following their natural purpose and find a lot of links that are broken and they are from the plain source files. However, **they are not broken after rendering** of the website's resources by Hugo.
> 
> For example, the Actions lists the logos in the root _index.md as `not found` with `src="/static/images/logos/huawei.logo.svg"`, which is correct because the logos are in `__/static/__images/logos/`. The rendered website displays the images without any issue.
> 
> Another example is `content/en/documentation/for-contributors/control-plane/_index.md`, where links to `entity.md` are identified as `not found`. On the website entity.md is rendered by Hugo as there is the sub-directory `./entity`, which includes all linked files and resources. From the website, again links are working fine as `./entity/_index.md` is rendered into `entity.md`..
> 
> I guess we need to find another approach of checking the links for this repository. Here such actions would just be usable for identifying links to other websites. With this approach, we are not really providing any support for contributors...
> 
> Any idea?

I've made some changes.

- Focused only on external links (HTTP/HTTPS)
- Improved caching configuration

2025-05-14 05:27 UTC, mspiekermann commented
@liugddx thanks a lot for the updates! I'll check asap to get the PR finally merged.

2025-08-21 15:37 UTC, liugddx commented on .github/workflows/check-broken-links.yaml
These two workflows ensure that external links in the documentation remain consistently valid and accessible by automatically checking and blocking invalid links during PRs, as well as periodically scanning the entire repository to create issues for tracking problems. One workflow operates in real-time but only applies to part of the documentation, while the other runs on a schedule and ensures that all links across the repository can be detected.

2025-08-22 04:49 UTC, liugddx commented
> @liugddx any news?

Please take a look

2025-08-25 13:03 UTC, ndr-brt approved these changes
LGTM, thanks!

2025-08-25 13:03 UTC, merged